services:
  api:
    container_name: rarity_api
    build:
      context: .
    restart: always
    command: ["poetry", "run", "uvicorn", "src.rarity_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    ports:
      - 8000:8000
    
    depends_on:
      - db
    volumes:
      - ./data/images:/src/rarity_api/images
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PROJECT_TITLE}-db:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'

volumes:
  rarity-api-db:
    name: ${PROJECT_TITLE}-db
